log:
  level: DEBUG

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: :443
    http:
      tls:
        certResolver: letsencrypt

certificatesResolvers:
  letsencrypt:
    acme:
      email: mark.plover13@gmail.com
      storage: /etc/certs/acme.json
      httpChallenge:
        entrypoint: web

api:
  insecure: true
  dashboard: true

providers:
  file:
    watch: true
    filename: /etc/traefik/config.yml
  docker: {}
